'''
Module: configuration_setup

The Config Object for Pipeline Execution of scanpy.

This module provides the functionality to configure and set up an ``experiment_dict`` object
for single-cell RNA sequencing (scRNA-seq) experiments. The ``get_config`` function in this
module is designed to generate a comprehensive configuration dictionary with predefined
sections for various steps of the scRNA-seq analysis pipeline, including quality control,
data scaling, normalization, clustering, and downstream analysis.

The configuration generated by this module is highly customizable and can be adapted to
specific experimental setups and analysis requirements. It allows for fine-tuning of
parameters related to data processing, gene selection, plotting options, and more.
Additionally, it provides support for both CPU and GPU processing, enabling efficient
handling of large-scale scRNA-seq datasets.

What to plot and what to save is handled by adata.uns["config"]["to_plot"] and adata.uns["config"]["to_create"].
The documentation for that will be available someday hopefully.

**Key Features:**
    - **Quality Control:** Configurable options for mitochondrial, ribosomal, and pseudogene
      filtering, with organism-specific presets for human and mouse.
    - **Data Scaling and Normalization:** Options to save and process different data layers,
      including counts, log-transformed data, and scaled data.
    - **Clustering and Downstream Analysis:** Comprehensive setup for unsupervised clustering
      using methods like Leiden, with support for visualizing UMAPs, heatmaps, and dot plots.
    - **Plotting Options:** Extensive configuration for generating various plots, including
      violin plots, scatter plots, dendrograms, and more, with the ability to customize
      color maps and plot aesthetics.
    - **GPU Support:** Enables GPU acceleration for clustering and UMAP calculation,
      improving performance on large datasets.

**Usage Notes:**
    - Users are encouraged to review and adjust the configuration settings to match their
      specific experimental needs. Critical settings such as save paths, data layers to save,
      and organism type should be carefully set.
    - NOTE: Some features and options in the configuration are marked as experimental or
      deprecated and should be used with caution. For instance, scaling and histogram
      equalization settings may require additional validation before use in analysis.
    - TODO: The module contains placeholders for future enhancements, such as support for
      additional organisms and more general keys for all analyses. Users contributing to the
      codebase should implement these features as needed.

**Dependencies:**
    - This module relies on external libraries, including Scanpy for scRNA-seq analysis and
      Matplotlib for plotting. Ensure all necessary packages are installed and up-to-date.
    - The module also references external paths for database files and gene sets. These paths
      should be correctly set up and accessible in the user's environment.

TODO: The module contains placeholders for future enhancements, such as support for
    additional organisms and more general keys for all analyses. Users contributing to the
    codebase should implement these features as needed.

    - If some collaborations require always the same setup, you can define it here:
        1. Create a function that adjusts the config:
            def param_your_colab_partners(config: experiment_dict) -> experiment_dict:
                config["whatever_to_change"] = "whatever"
                return config

        2. Run the function conditionally in ``get_config``:
            if param_setup == "your_colab_partners":
                config = param_your_colab_partners(config)

**Examples:**
Here are a variety of examples illustrating how to modify the configuration for a Scanpy
single-cell analysis. These examples cover common adjustments as well as more advanced
customizations.

.. code-block:: python

    >>> # Don't plot the leiden and sample umap
    >>> adata.uns["config"]["to_plot"]["down"]["visualize_leiden_umap"] = False
    >>> # Plot the Quality measures on the umap
    >>> adata.uns["config"]["to_plot"]["down"]["visualize_qc_umap"] = True
    >>> # save the DEGs as csvs
    >>> config["to_create"]["down"]["DEG_csv"]["create"] = True
    >>> # Don't save the clustering stats as csvs
    >>> config["to_create"]["down"]["cluster_stats_csv"]["create"] = False

Please add the config object to the adata.uns["config"].
This small example load the library, create a default object and save it to the adata object.

.. code-block:: python

    >>> # Load the library
    >>> from scToolkit import sc_config, sc_utils
    >>> # Enable cuda support for the code
    >>> sc_utils.initialize_cuda()
    >>> # Create the config object
    >>> config = sc_config.get_config(
    ...     param_setup="default",
    ...     dataset_name="your_dataset_or_experiment_name",
    ...     save_path="path_to_the_analysis_output",
    ...     use_GPU=True)
    >>> # add the config object to the adata
    >>> adata.uns["config"]

If you want to change the standard parameters of any scanpy function you can change it like e.g.

.. code-block:: python

    >>> # Change the minimum genes to filter cells
    >>> adata.uns["config"]["pp"]["filter_cells"]["min_genes"] = 500
    >>> # Change the maximum Mitochondrial content to filter cells
    >>> adata.uns["config"]["pp"]["filter_qc_var_obs"]["max_pct_MT"] = 8
    >>> # Change the QC key to plot violins
    >>> adata.uns["config"]["general"]["keys_for_qc"]["obs"] = ["pct_MT", ...]
    >>> adata.uns["config"]["general"]["keys_for_qc"]["var"] = ["n_cells", ...]

The config object also contains function, which are not h5ad/json serializable!
Therefore use the scToolkit saving and loading functions please!

Examples::
    NOTE:
        - Here we will use config which is synonymus for adata.uns["config"]
        - BUT keep in mind config = adata.uns["config"] is a symbolic link if you change config,
          it will also change the adata.uns["config"].

1.1.  **Save the adata and the config:**

.. code-block:: python

    >>> # no compression is faster, but more disk space required
    >>> sc_utils.save_h5ad(adata, "path/to/adata.h5ad", compression=None)
    >>> # Load the adata and the config
    >>> adata = sc_utils.load_h5ad("path/to/adata.h5ad")

1.2. **Enable GPU acceleration for neighbors computation:**

.. code-block:: python

    >>> # Set automatically everything to GPU usage
    >>> config = get_config(use_GPU=True)
    >>> # All methods support manual changing from change_gpu_usage():
    >>> # #########################################################
    >>> # Set general GPU usage flag in the configuration
    >>> adata.uns["config"]["general"]["use_GPU"] = "True" if enable else "False"
    >>> # #########################################################
    >>> # Configure GPU acceleration for individual components
    >>> # ##########################################
    >>> # Configure PCA computation method
    >>> if "pca" in to_enable:
    ...     adata.uns["config"]["pp"]["pca"]["method"] = "rapids" if enable else "pca"
    >>> # ##########################################
    >>> # Configure Leiden clustering method
    >>> if "leiden" in to_enable:
    ...     adata.uns["config"]["tl"]["umap"]["method"] = "rapids" if enable else "umap"
    >>> # ##########################################
    >>> # Configure nearest neighbors computation method
    >>> if "neighbors" in to_enable:
    ...     adata.uns["config"]["tl"]["leiden"]["method"] = "rapids" if enable else "leiden"
    >>> # ##########################################
    >>> # Configure UMAP embedding method
    >>> if "umap" in to_enable:
    ...     adata.uns["config"]["pp"]["neighbors"]["transformer"] = "rapids" if enable else "sklearn"

1.3. **Update the save path and enable overwriting existing results:**

.. code-block:: python

    >>> # Set the save path
    >>> config = get_config(save_path="/path/to/save", overwrite=True)
    >>> # change the save path
    >>> # DON'T do: config["general"]["save_path"] = ... it won't create the folder!
    >>> # USE:
    >>> sc_config.set_save_path("/path/to/save", overwrite=True)

1.4. **Increase the number of cores used for parallel processing:**

.. code-block:: python

    >>> # This is unfortunately is only for the scanpy methods that support parallelization
    >>> # basically the ones we don't advise you to use: draw_graph, tsne, regress_out
    >>> config = get_config(n_cores=40)
    >>> # To set the generall number of threads used by python
    >>> utils.set_threads(40)
    >>> # NOTE: A pc is doing many things aside, dont use 40 if you only have 40 cores,
    >>> #       leave some cores for the system

1.5. **Set the random seed for reproducibility across all steps (non GPU only!):**

.. code-block:: python

    config["general"]["seed"] = 12345  # Default is 42

1.6. **Set the organism type to "mouse" and adjust QC gene identifiers:**
    Manually setting is not necessary, due to automation, but you can add new regex.

    NOTE:
        THIS MUST HAPPEN AFTER YOU run the setup_adata and before sc_code.all_qc_preprocessing(adata)

.. code-block:: python

    >>> config = setup_adata(organism="mouse")
    >>> config["qc"]["gene_identifiers"][config["general"]["mitochondiral_key"]] = "^mt-"
    >>> config["qc"]["gene_identifiers"][config["general"]["your_genes"]] = "^Cd"
    >>> sc_code.all_qc_preprocessing(adata)

1.6.2. **Specify a custom set of mitochondrial genes for QC filtering in Regex (^ for start | for or $ for end):**
    NOTE:
        THIS MUST HAPPEN AFTER YOU run the setup_adata and before sc_code.all_qc_preprocessing(adata)

.. code-block:: python

    >>> config["qc"]["gene_identifiers"]["MT"] = "$|^".join(["MT-ND1", "MT-ND2", "MT-CO1"])
    >>> sc_code.all_qc_preprocessing(adata)

1.7. **Enable/disable saving of data in the layers:**

.. code-block:: python

    >>> config["general"]["save_counts"] = True
    >>> config["general"]["save_norm_counts"] = True
    >>> config["general"]["save_normlog2_counts"] = True
    >>> config["general"]["save_regress_out"] = False  # NO ARBITRARY DATA RESCALING!!!!
    >>> # NOTE: Scaled is the same as z-score transformation, good for plotting dotplots or heatmaps
    >>> config["general"]["save_scaled"] = True

1.8. **Disable/Enable the saving of intermediate QC counts data:**
    Everything is relative. If you want to look for douplets,
    the pct-MT won't help but maybe the total_counts_MT can.

.. code-block:: python

    >>> config["general"]["del_qc_counts"] = True

1.9. **Filter out low-quality cells based on gene count thresholds:**
    Here you have 2 options, manuall subsetting or with the function.

.. code-block:: python

    >>> config["pp"]["filter_cells"]["min_genes"] = 200
    >>> config["pp"]["filter_cells"]["max_genes"] = 6000
    >>> # ##############################
    >>> # Tag the cells
    >>> sc_code.all_filters_tagging(adata, reset=True)
    >>> # Manual subsetting
    >>> adata = adata[adata.obs["good_quality"], adata.var["good_quality"]].copy()
    >>> # ##############################
    >>> # Tag the cells and subset NOTE: IT RETURNS THE FILTERED OBJECT "adata =" is needed!
    >>> adata = sc_code.all_filters_tagging(adata, reset=True, apply_filters=True)

1.10. **Exclude specific gene families from analysis using a regular expression:**
    NOTE:
        This must happen before running sc_code.Run_all_prep_steps_clustering(adata) for automatic handling!

.. code-block:: python

    >>> config["exclude_gene_family_regex"] = "^MT-|*\\.1$"
    >>> adata = sc_code.Run_all_prep_steps_clustering(adata)

2.1. **Change the method for calculating differentially expressed genes (DEGs):**

.. code-block:: python

    >>> config["tl"]["rank_genes_groups"]["method"] = "wilcoxon"  # USE "wilcoxon" for good!!!!!!!!!!!!

2.2. **Modify the list of highly variable genes by force including marker genes:**
    Doesn't acutally make sense, but if Colab partners "Know" which genes are interesting,
    beeing unbiased is for loosers, who will never publish anything.

.. code-block:: python

    >>> config = get_config(use_highly_variable_plus_marker_genes=True, marker_genes=["CD4", "CD8"])

2.3. **Customize the violin plot settings for QC analysis:**
    # This will be used as defaults for all violinplots, unless you use the function argument groupby

.. code-block:: python

    >>> # produce the Violin plots in run_downstream
    >>> config["to_plot"]["qc"]["all_violins"] = True
    >>> config["pl"]["violin"]["groupby"] = "cell_type"

3.1. **Change the number of to calculate principal components for PCA:**

.. code-block:: python

    >>> config["pp"]["pca"]["n_comps"] = 50  # Default is all: min(n_cells, n_genes) - 1

3.2. **Enable automatic PCA variance selection based on cumulative differences:**

.. code-block:: python

    >>> config["general"]["use_automatic_pca_variance_sum"] = "cumsum_diffs"
    >>> config["general"]["pca_variance_sum"] = 0.95

3.3. **Modify the metrics used in neighbors computation:**

.. code-block:: python

    >>> config["pp"]["neighbors"]["metric"] = "cosine"  # Default is "euclidean"

3.4. **Set a custom number of neighbors to use for neighborhood graph, impacts leiden and UMAP:**

.. code-block:: python

    >>> config["pp"]["neighbors"]["n_neighbors"] = 15  # Default is 20

3.5. **Adjust the UMAP settings to change the minimum distance and spread:**

.. code-block:: python

    >>> config["tl"]["umap"]["min_dist"] = 0.1  # Default is 0.5
    >>> config["tl"]["umap"]["spread"] = 1.5    # Default is 1.0

3.6. **Change the clustering resolution for Leiden algorithm:**

.. code-block:: python

    >>> config["tl"]["leiden"]["resolution"] = 1.0  # Default is 0.75

3.5. **Set the key for clustering to use a different method:**

.. code-block:: python

    >>> config["general"]["cluster_algorithm"] = "leiden"  # There is no alternative!

4.1. **Specify a subset of markers to be used for heatmap visualization for run_downstream:**

.. code-block:: python

    >>> config["to_plot"]["down"]["heatmaps"]["marker_mod"] = ["CD4", "CD8", "GATA3"]

4.2. **Set the color map for run_downstram for all heatmap/all in general to "viridis"/"turbo":**

.. code-block:: python

    >>> config["pl"]["heatmap"]["cmap"] = "viridis"
    >>> # Or overwrite all
    >>> sc_config.update_key_in_config(adata_.uns["config"], key_to_update="cmap", new_value="turbo")
    >>> # THIS HAS TO BE USED WITH EXTREME CONCIOUSNESS and only used for plotting
    >>> # arguments or useless scanpy thing like overwriting "use_raw" = False

4.3. **Set the filtering criteria for the creation of a DEGs CSV/xlsx:**

.. code-block:: python

    >>> # NOTE: An LFC (log2) from 1 to 2 is already 1... quite uninformative as a single measure!
    >>> config["to_create"]["down"]["DEG_csv"]["log2fc_min"] = 1.0
    >>> # This is actually the adjusted, nobody is interested it the actual pval.
    >>> config["to_create"]["down"]["DEG_csv"]["pval_cutoff"] = 0.0001
    >>> # percentage of cells that must express the genes in eighter group
    >>> config["to_create"]["down"]["DEG_csv"]["pct_min"] = .1
    >>> # which table type to save is handled by:
    >>> config["general"]["save_df_types"] = [".csv", ".xlsx"]
    >>> # available types: '.csv' ,'.xlsx' ,'.json' ,'.html' ,'.feather' ,'.parquet' ,'.pkl' ,'.pickle'

4.4. **Adjust the heatmap parameters to visualize the top 50 genes for run_downstream:**

.. code-block:: python

    >>> config["to_plot"]["down"]["heatmaps"]["DEG_params"]["top_n_genes"] = 50  # Default is 20

4.5. **Customize the dendrogram visualization for marker genes:**

.. code-block:: python

    >>> config["to_plot"]["down"]["marker_dendrograms"]["visualize"] = True
    >>> config["to_plot"]["down"]["marker_dendrograms"]["figsize_small"] = [12, 8]  # Default is [10, 7]

4.6. **Enable or disable the plotting of UMAP visualizations for run_downstream:**

.. code-block:: python

    >>> config["to_plot"]["down"]["umap"] = False  # Disable UMAP plotting

4.7. **Enable plotting of cluster-specific dot plots for run_downstream:**

.. code-block:: python

    >>> config["to_plot"]["down"]["cluster_dotplot"]["visualize"] = True

4.8. **Define a custom colormap for specific plots:**

.. code-block:: python

    >>> custom_cmap = ListedColormap(["#FF0000", "#00FF00", "#0000FF"])
    >>> config["pl"]["dotplot"]["cmap"] = custom_cmap

4.9. **Change the default color palette for cell type annotations for run_downstream:**

.. code-block:: python

    >>> custom_palette = ["#FF0000", "#00FF00", "#0000FF"]
    >>> config["pl"]["scatter"]["palette"] = custom_palette

These examples Illustrate the flexibility of the configuration setup,
allowing users to tailor the analysis pipeline to their specific
requirements. By adjusting these parameters, you can ensure that the
analysis is customized to your experimental needs and preferences.
To make full use of this flexibility, it is ESSENTIAL to understand the
configuration structure and consult the documentation carefully.

This module is intended for advanced users familiar with scRNA-seq data analysis and Python
programming. Proper understanding and careful configuration of the parameters are essential
for successful application of the provided functions.

If you something is missing or you want to incorporate different scverse libraries
please feel free to contact the single cell Responsibles.
(If it is Machine learning related, don't even ask, it won't be incorporated, PCA is bad enough already!)

# TODO: add a cell cycle geneset or genesets for each cell cycle phase
# TODO: add a function to disable/enable GPU

══════════════════════════════════════════════════
══════════════════════════════════════════════════
'''

from scToolkit import (
    # Standard Library Imports
    os, compile, Mapping,  # re,
    # Pandas and NumPy for data manipulation and analysis
    np, pd,
    # Matplotlib for plotting and visualization
    colormaps,  # LinearSegmentedColormap, ListedColormap, cm,
    # ##########################
    # scToolkit specifics
    # Logging and Configuration Functions
    get_logger, ALL_PATHS, GENESET_FILENAMES, create_code_structure)

# From this repo
logger = get_logger(name="sc_config")


class experiment_dict(dict):
    """This class stores the parameter setup for a single-cell experiment.

    The experiment_dict class is designed to handle various configuration
    settings for a single-cell experiment, including quality control (QC)
    parameters, downstream analysis setups, and plot settings. The dictionary is
    structured to accommodate different stages of the data processing pipeline,
    with distinct sections for each major step.

    Attributes:
        general (dict): A dictionary to store general experiment settings.
        qc (dict): A dictionary to store quality control parameters, including
            gene identifiers.
        downstream (dict): A dictionary to store downstream analysis
            configurations.
        scToolkit (dict): A dictionary to store settings related to the Scanpy
            API.
        to_plot (dict): A nested dictionary to store plotting configurations for
            different stages.
        to_create (dict): A nested dictionary to store configurations for items
            to be created, such as DEG CSVs.

    Returns:
        None

    Tags:
        config
    """
    def __init__(self) -> None:
        """Initializes the experiment_dict with predefined sections for different processing steps."""
        super().__init__()
        # #########################################################
        # Create the general dictionary
        self["general"] = {}
        # #########################################################
        # Create dictionaries for different processing steps
        # qc: Quality control section, includes gene identifiers
        self["qc"] = {"gene_identifiers": {}}

        # downstream: Downstream analysis section
        self["downstream"] = {}

        # scToolkit: scToolkit related settings
        self["scToolkit"] = {}
        # #########################################################
        # Creating nested dictionaries for plotting and creating outputs
        # TODO: move this outside of the get_dict, but into the init.
        self["to_plot"] = {
            "qc": {},
            "cl": {},
            "down": {
                "marker_dendrograms": {},
                "gradients_umap": {"include_mod_variables": {}},
                "cluster_dotplot": {},
                "rank_genes_groups": {},
                "cell_type_score_umap": {},
                "cluster_violins": {},
                "heatmaps": {}}}
        self["to_create"] = {
            "down": {
                "DEG_csv": {},
                "marker_csv": {},
                "cluster_stats_csv": {}}}

    def set_save_path(
                self,
                save_path: str,
                overwrite: bool
            ) -> None:
        """Sets the save path for the experiment data.

        Args:
            save_path (str): The directory path where the experiment data should be saved.
            overwrite (bool): Flag indicating whether to overwrite existing directories.

        Raises:
            OSError: If the directory cannot be created and does not already exist.

        NOTE:
            The save_path is trimmed of trailing slashes and updated with a unique identifier if
            overwrite is set to False and the directory already exists.
        """
        # #########################################################
        # Normalize save_path by removing trailing slash
        if save_path[-1] == "/":
            save_path = save_path[:-1]
        # #########################################################
        # Ensure unique save path if not overwriting
        i = 0
        while os.path.exists(save_path) and not overwrite:
            if i > 0:
                save_path = save_path[:-2]
            save_path += f'_{i}'
            i += 1
        save_path += "/"
        # #########################################################
        # Create the directory if it doesn't exist
        if not os.path.exists(save_path):
            os.makedirs(save_path)

        self["general"]["save_path"] = save_path

    def sync_dict(self, dictionary: dict) -> None:
        """Synchronizes the current experiment dictionary with another dictionary.

        Args:
            dictionary (dict): The dictionary to sync with.

        NOTE:
            DEPRECATED!!! This method resets the save path and calculates
            non-overlapping keys between the current dictionary and the provided
            one. The non-overlapping keys are stored under 'non_overlap'.
        """
        # #########################################################
        # Reset the save path using the provided dictionary
        self.set_save_path(dictionary["general"]["save_path"], dictionary["general"]["overwrite"])
        # #########################################################
        # Identify and store non-overlapping keys
        non_overlap = [k for k in dictionary.keys() if k not in self.keys()]
        if len(non_overlap) > 0:
            logger.info("There are non overlapping keys while syncing. The keys are saved in 'non_overlap'")
            self["non_overlap"] = non_overlap
        # #########################################################
        # Replace the current dictionary elements with the provided dictionary's elements
        for k, v in dictionary.items():
            self[k] = v


def get_config(
            param_setup: str = "default",
            experiment_name: str = "default",
            dataset_name: str = "default",
            save_path: str = "./analysis/",
            use_rna: bool = True,
            use_prot: bool = False,
            analysis_only: bool = False,
            overwrite: bool = True,
            marker_genes: list[str] = [],
            organism: str = "human",
            use_highly_variable_plus_marker_genes: bool = False,
            use_GPU: bool = True,
            n_cores: int = 20,
            selected_citeseq_markers: list[str] = [],
            selected_gene_markers: list[str] = []
        ) -> dict:
    """Generates a configuration dictionary for single-cell analysis.

    This function initializes and returns a configuration dictionary for setting
    up a single-cell analysis pipeline. The configuration includes general
    processing parameters, dataset-specific settings, quality control settings,
    clustering preferences, and visualization options.

    NOTE:
        - Scaled values are computed as z-score transformations and are useful
          for dot plots or heatmaps.
        - If ``use_highly_variable_plus_marker_genes`` is set, marker genes will
          be included in the highly
          variable gene selection.
        - GPU processing is available but starts with clustering.

    Args:
        param_setup (str, optional): Defines the parameter setup name.
            Defaults to "default".
        experiment_name (str, optional): Name of the experiment.
            Defaults to "default".
        dataset_name (str, optional): Name of the dataset.
            Defaults to "default".
        save_path (str, optional): Directory path to save outputs.
            Defaults to "./analysis/".
        use_rna (bool, optional): Whether to use RNA-based analysis. Default is
            True. Defaults to True.
        use_prot (bool, optional): Whether to include protein-based analysis.
            Default is False. Defaults to False.
        analysis_only (bool, optional): If True, skips all plotting. Default is
            False. Defaults to False.
        overwrite (bool, optional): If True, overwrites existing results.
            Default is True. Defaults to True.
        marker_genes (list[str], optional): List of marker genes to consider.
            Defaults to [].
        organism (str, optional): Specifies the organism (e.g., 'human',
            'mouse'). Default is 'human'. Defaults to "human".
        use_highly_variable_plus_marker_genes (bool, optional): If True,
            includes marker genes in highly variable genes. Defaults to False.
        use_GPU (bool, optional): Whether to use GPU acceleration. Default is
            True. Defaults to True.
        n_cores (int, optional): Number of CPU cores to use. Default is 20.
            Defaults to 20.
        selected_citeseq_markers (list[str], optional): Selected CiteSeq
            markers. Defaults to [].
        selected_gene_markers (list[str], optional): Selected gene markers.
            Defaults to [].

    Returns:
        dict:
            A configuration dictionary for the analysis pipeline.

    Raises:
        NotImplementedError: If an unsupported organism is provided.

    Calls:
        dataset_to_dict, experiment_dict.set_save_path

    Called By:
        load_h5ad_old, setup_adata

    TODO:
        Implement organism support for species other than human and mouse.

    Tags:
        DEG, QC, annotation, clustering, config, normalization, scaling, stats,
        visualization
    """
    config = experiment_dict()
    # #############################################
    # Super General stuff!
    # Please take time to make sure to set this parameters right
    # Key for differentiating the samples/replicates
    sample_key = []
    # Key for the mitochondiral genes
    mitochondiral_key = "MT"
    # Key for the Ribosomal Genes
    ribosomal_key = "RBS"
    # Key for the Mito-Ribosomal genes
    mito_ribosomal_key = "MTRBS"
    # Key for the pseudo genes
    pseudogene_key = "PSEUDO"
    # Key for the Housekeeping Genes
    house_keeping_key = "HK"
    # Key for the Hemoglobin Genes
    hemoglobin_key = "HG"

    # Default color map, if R use the R default
    cmap = "R"
    # Check if colormap exist
    if cmap not in colormaps() or cmap == "R":
        cmap = "R"

    # General Stuff
    # which layers should be calculated and saved
    config["general"]["n_cores"] = n_cores
    config["general"]["save_counts"] = True
    config["general"]["save_norm_counts"] = True
    # You should save this for sure to replace X after clustering with the unscaled version
    config["general"]["save_normlog2_counts"] = True
    config["general"]["save_regress_out"] = False
    # Optionaly save the non normed log1p counts
    config["general"]["save_log2_counts"] = False
    # NOTE: Scaled is the same as z-score transformation, only good for PCA preprocessing.
    config["general"]["save_scaled"] = True
    # TODO: this is experimental and not standardized, please test for clustering
    config["general"]["save_histeq_counts"] = False
    # ########################
    # SCALING
    # if you scale the data, make sure to replace the adata.X with the normalized log2 layer for deg calculations
    config["general"]["scale_data"] = True
    config["general"]["scale_data_prot"] = True
    # ########################
    # Remove the gene family tags
    config["general"]["keep_qc_var_gene_identifiers"] = False
    # ########################
    # Genen removal or tagging
    config["general"]["only_mask_genes"] = False
    # ########################
    # QC
    # Save also the count values for the qc measures if False
    config["general"]["del_qc_counts"] = True
    # We calculate many qc keys and only a small subset is general and necessary
    # for qc, the usefull will be saved in  config["general"]["keys_for_qc"]
    # all will be saved in config["general"]["keys_for_qc_all"]
    config["general"]["qc_keys_to_keep"] = {"obs": [], "var": []}
    # NOTE: you need to update this after adding a new database to the paths.py
    # HIGHLIGHTER: XXXDATABASE_UPDATEXXX
    if organism == "human":
        config["general"]["qc_keys_to_keep"]["obs"] = [
            'n_genes', 'n_counts', 'n_unique', 'max_count', 'top_10_ratio',
            'pct_HK_gtex', 'pct_HK_cellminer', 'pct_HK_klijn', 'pct_HK_human',
            'pct_HK_hrt', 'pct_HK_hk_union', 'pct_HK_hk_intersect',
            'pct_GTF_IG_genes', 'pct_GTF_processed_transcripts',
            'pct_GTF_TR_genes', 'pct_GTF_protein_coding',
            'pct_HGNC_non_coding_RNA', 'pct_HGNC_pseudogene', 'pct_MT',
            'pct_RBS', 'pct_HG']
    elif organism == "mouse":
        config["general"]["qc_keys_to_keep"]["obs"] = [
            "n_genes", "n_counts", "n_unique", "max_count", "top_10_ratio",
            "pct_HK_mousekeeping", "pct_HK_hrt", "pct_GTF_IG_genes",
            "pct_GTF_processed_transcripts", "pct_GTF_TR_genes",
            "pct_GTF_RBS", "pct_GTF_protein_coding", "pct_MGI_Gene",
            "pct_MGI_Pseudogene", "pct_MT", "pct_HG"]
    # ########################
    # Sometimes for the unsupervised clustering it helps to remove genes or gene families.
    # NOTE: you can eighter use exclude_gene_family_regex or one of the other two!
    # Here you directly specigy the genes
    config["exclude_genes"] = []
    # Here you sepcify a start like e.g "MT-"
    config["exclude_gene_family"] = []
    # Here you use a regex, ^ marks the start, | is alternative, $ is end and . is anything, * allows 0-inf repetitions + 1-inf.  # noqa: E501
    # E.G search for all genes starting with MT- and all genes ending with .1 is: "^MT-|\.1$"
    config["exclude_gene_family_regex"] = None
    config["exclude_gene_family_regex_from_highly_variable"] = None
    # ########################
    # Other things you may (or better may not consider to change)
    config["general"]["hist_eq"] = False
    config["general"]["normalize_cell_size"] = True
    config["general"]["logarithmize"] = True
    config["general"]["regress_out"] = False
    config["general"]["cluster_algorithm"] = "leiden"
    # ###############################################################
    # For analysis purposes save the umap temporary
    config["general"]["save_umap_object"] = {}
    config["general"]["save_umap_object"]["to_save"] = True
    config["general"]["save_umap_object"]["key"] = "UMAP"
    # ###############################################################
    # save dataframes as
    config["general"]["save_df_types"] = [".csv", ".xlsx"]
    # ###############################################################
    # Create a stat csv for the clusterings and each modality
    config["general"]["save_cluster_stats"] = True
    # #############################################
    # Create a entry for the marker genes, that should be excluded from filtering.
    # NOTE: This is biased, maybe only valid for super rare celltypes like liquid biopsies
    # TODO: This is furthermore not implemented anymore, due to efficience. If you find a good solution reimplement it.
    #       One opportunity would be get the adata object for this genes and merge on inner join
    #       the filtered with this one afterwards.
    config["marker_genes_to_exclude_from_filtering"] = []  # marker_genes
    # #############################################
    if use_highly_variable_plus_marker_genes:
        config["marker_genes_to_include_in_highly_variables"] = marker_genes
    else:
        config["marker_genes_to_include_in_highly_variables"] = []
    # ############################################
    # Path to the database files
    config["general"]["path_to_database"] = ALL_PATHS["PATH_TO_DATABASE"]
    # #############################################
    # Choose the Organism to work on. This sets the Mitochondrial, Ribosomal and Pseudogenes
    # TODO: Implement this for mouse!
    # TODO: Get a complete list of pesudo genes!
    config["general"]["organism"] = organism
    # #############################################
    config["general"]["filter_highly_variable"] = False
    # ########################
    # Dataset Specifics
    config["dataset_name"] = dataset_name
    config["use_prot"] = use_prot
    config["use_rna"] = use_rna
    # Subsetted marker gene lists for very large number of cell types or many markers per cell type
    # selected_citeseq_markers = [
    #         "GPR56_CITESEQ", "CD45RA_CITESEQ", "CD71_CITESEQ", "TCRVa7_2_CITESEQ",
    #         "CD161_CITESEQ", "TCRVd2_CITESEQ", "CD4_CITESEQ", "CD8_CITESEQ",
    #         "CD95_CITESEQ", "CD45RO_CITESEQ", "CD57_Recombinant_CITESEQ", "CD45R_CITESEQ"]
    # selected_gene_markers = [
    #         "CD4", "CD8", "GATA3", "IFNG", "GZMB", "GZMK", "GZMH", "ZEB2", "KLRG1", "NKG7",
    #         "CD38", "ANXA2", "CD27", "CD28", "POU2AF1", "IL10", "CAV1", "CD81", "EOMES", "TBX21", "IL32",
    #         "KLRD1", "NR4A2", "KLRB1", "FAS", "CTLA4", "FOXP3", "IKZF2",  "IL7R", "CCR7",  "SELL", "LEF1",
    #         "TCF7", "FOXP1", "BCL6", "CXCR3", "SOCS3", "GNLY", "LAG3",  "B3GAT1",  "IKZF3", "HNRNPLL"]
    combined_selected_markers = [*selected_citeseq_markers, *selected_gene_markers]
    # #############################################
    # Experiment specific naming and parameter setups
    config["experiment_name"] = experiment_name
    config["param_setup"] = param_setup
    # #############################################
    # Create a folder to save results
    config.set_save_path(save_path, overwrite)
    # THIS SHOULD BE USED WITH CAUTION, BECAUSE IT OVERWRITES ALL EXISTING ANALYSIS!!!
    config["general"]["overwrite"] = overwrite

    # If this variable is false, don't show any plot, but it could produce
    # saved figures based on config["general"]["save_figures"]
    config["general"]["show_plots"] = True
    # config["general"]["show_all"] = False
    config["general"]["analysis_only"] = analysis_only  # If this variable is false, skip all the plotting
    # DEBUG FUNCTION, if false, doesn't save any figures
    # If ture it enables the saving functionaliry, what should be saved,
    # will be decided by the settings in config["to_plot"]
    config["general"]["save_figures"] = True
    # The seed for random processes
    config["general"]["seed"] = 42
    # For automatic PCA selection, defaults to 95% of the cumulative differences in observed variance
    config["general"]["pca_variance_sum"] = .95
    config["general"]["use_automatic_pca_variance_sum"] = "cumsum_diffs"
    # ############################################################################################
    # Define Which plots to plot:
    # QC
    # Violin plots for the distributions in config["general"]["keys_for_qc"]
    config["to_plot"]["qc"]["all_violins"] = True
    # Scatter plots for n_counts vs n_genes with colors in config["general"]["keys_for_qc"]
    config["to_plot"]["qc"]["all_gene_counts_scatters"] = False
    # Scatter plots all combinations in config["general"]["keys_for_qc"]
    # TODO: visualize them and check which makes sense to show also show the clustering for outlier detection
    config["to_plot"]["qc"]["all_combination_scatters"] = False
    # Density Scatter plots for n_counts vs n_genes
    config["to_plot"]["qc"]["densiry_scatters"] = True
    # ############################################################################################
    # CLUSTERING
    # visualize the clustering and samples
    config["to_plot"]["down"]["visualize_leiden_umap"] = True
    config["to_plot"]["cl"]["visualize_embedding_density_umap"] = True
    config["to_plot"]["down"]["visualize_qc_umap"] = True
    config["to_plot"]["cl"]["visualize_pca_variance_ratio"] = False
    # ############################################################################################
    # DOWNSTREAM
    # If your marker genes are large and you only want to plot a selected subset of the markers
    # NOTE: this doesn't have to be actual markers, can also be used for genes of interest.
    # This will be used for the marker_heatmaps, marker_dotplot,
    config["to_plot"]["down"]["marker_subset"] = combined_selected_markers
    # #####################################
    # Dendrograms
    # this enables the general option to visualize the dendrogram
    config["to_plot"]["down"]["marker_dendrograms"]["visualize"] = False
    # these are dicts with modalities
    config["to_plot"]["down"]["marker_dendrograms"]["marker_mod"] = []  # ["rna", "prot", "comb"]
    config["to_plot"]["down"]["marker_dendrograms"]["selected_marker_mod"] = []  # ["rna", "prot", "comb"]
    config["to_plot"]["down"]["marker_dendrograms"]["geneset_threshold"] = 30
    config["to_plot"]["down"]["marker_dendrograms"]["figsize_small"] = [10, 7]
    config["to_plot"]["down"]["marker_dendrograms"]["figsize_large"] = [15, 7]
    # ############################################################################################
    # Enable or disable all umap plotting
    config["to_plot"]["down"]["umap"] = True

    # Gradient UMAPs
    # this enables the general option to visualize the dendrogram
    config["to_plot"]["down"]["gradients_umap"]["visualize"] = True
    # ##############
    # Which genes/variables to include

    # include_marker == "all" used the config["to_plot"]["down"]["gradients_umap"]["include_mod_variables"]["rna"]
    # include_marker == "subset" used the config["to_plot"]["down"]["marker_subset"]
    # include_marker == "ref_dict" used the ref_dict and plots per cell type and the number of genes can be
    #                              setted with config["to_plot"]["down"]["gradients_umap"]["num_ref_genes"]
    # #############
    # General if discrete or continuos
    # Plot the gradient continuos
    config["to_plot"]["down"]["gradients_umap"]["continuos"] = True
    # Optionally plot the gradient umaps in discretized version
    config["to_plot"]["down"]["gradients_umap"]["discretize"] = True
    # #############
    # use pre defined markers, eighter all or subset in one or per reference in ref_dict
    config["to_plot"]["down"]["gradients_umap"]["include_marker"] = "ref_dict"  # "all", "subset"
    config["to_plot"]["down"]["gradients_umap"]["num_ref_genes"] = 10
    # #############
    # use highly variable
    config["to_plot"]["down"]["gradients_umap"]["include_highly_variable"] = True
    # use your choice of markers
    config["to_plot"]["down"]["gradients_umap"]["include_mod_variables"]["rna"] = []
    config["to_plot"]["down"]["gradients_umap"]["include_mod_variables"]["prot"] = []
    # For the highly variable, choose top n highly variable gense
    config["to_plot"]["down"]["gradients_umap"]["num_highly_variable"] = 10
    # #############
    # For the DEGs
    config["to_plot"]["down"]["gradients_umap"]["include_DEG_variables"] = ["rna"]
    config["to_plot"]["down"]["gradients_umap"]["plot_per_group_DEG_umaps"] = {
        "perc": .1, "p_val_cutoff": .01, "overlap_fill_to_top_n": True, "lfc": 1,
        "direction": "up_n_down"}
    config["to_plot"]["down"]["gradients_umap"]["num_DEGs"] = 10
    # ############################################################################################
    # Visualize the top_k DEGs over as dotplots over clusters
    config["to_plot"]["down"]["cluster_dotplot"] = {}
    config["to_plot"]["down"]["cluster_dotplot"]["visualize"] = True
    # ################################
    # Visualize the DEGs expression violins per cluster
    config["to_plot"]["down"]["cluster_dotplot"]["n_DEGs"] = [10]
    # Thresholds for visualization
    config["to_plot"]["down"]["cluster_dotplot"]["plot_per_group_DEG_dotplot_n_gene_dendrogram"] = {
            "highly_variable": False, "var_dendrogram": False,
            "split_on": 30, "perc": .1, "p_val_cutoff": .01, "overlap_fill_to_top_n": True, "lfc": 1,
            "direction": "up_n_down"}
    # ################################
    # Modalitys to plot
    config["to_plot"]["down"]["cluster_dotplot"]["marker_mod"] = ["rna"]  # , "prot", "comb"]
    config["to_plot"]["down"]["cluster_dotplot"]["marker_mod_per_cluster"] = ["rna"]  # , "prot", "comb"]
    config["to_plot"]["down"]["cluster_dotplot"]["marker_subs_mod"] = []   # , "prot", "comb"]
    config["to_plot"]["down"]["cluster_dotplot"]["marker_subs_mod_per_cluster"] = []  # , "prot", "comb"]
    # If the hole plot should be flipped
    config["to_plot"]["down"]["cluster_dotplot"]["swap_axes"] = False
    # ############################################################################################
    # Visualize the DEGs expression violins per cluster
    config["to_plot"]["down"]["cluster_violins"]["visualize"] = True
    # Modalitys to
    config["to_plot"]["down"]["cluster_violins"]["DEG_mod"] = ["rna"]  # ["rna", "prot", "comb"]
    config["to_plot"]["down"]["cluster_violins"]["n_DEGs"] = [20]
    config["to_plot"]["down"]["cluster_violins"]["plot_per_group_stacked_violins"] = {
        "perc": .1, "p_val_cutoff": .01, "overlap_fill_to_top_n": True, "lfc": 1,
        "direction": "up_n_down"}
    # TODO: implement the marker subset mod
    # ["rna", "prot", "comb"]
    # ############################################################################################
    # Visualize Ranked genes in plots
    config["to_plot"]["down"]["rank_genes_groups"]["visualize"] = False
    # Modalitys to plot
    config["to_plot"]["down"]["rank_genes_groups"]["marker_mod"] = []  # ["rna", "prot", "comb"]
    # ############################################################################################
    # Visualize the DEGs expression violins per cluster
    config["to_plot"]["down"]["cell_type_score_umap"]["visualize"] = True
    # Modalitys to plot
    config["to_plot"]["down"]["cell_type_score_umap"]["marker_mod"] = ["rna"]  # , "prot", "comb"]
    # ############################################################################################
    # Visualize heatmaps based on medioids subclustering
    config["to_plot"]["down"]["heatmaps"] = {}
    config["to_plot"]["down"]["heatmaps"]["visualize"] = False
    config["to_plot"]["down"]["heatmaps"]["title"] = {"marker": "heatmap_marker_genes",
                                                      "deg": "heatmap_DEG"}
    config["to_plot"]["down"]["heatmaps"]["marker_mod"] = []  # ["rna"]  # ["comb", "rna", "prot"]
    config["to_plot"]["down"]["heatmaps"]["marker_subs_mod"] = []  # ["rna"]  # ["comb", "rna", "prot"]

    config["to_plot"]["down"]["heatmaps"]["DEG_mod"] = ["rna"]  # ["comb", "rna", "prot"]

    config["to_plot"]["down"]["heatmaps"]["medioid_params"] = {
            "show_min": 20, "use_scale": False, "scaler": .05,
            "cluster_key": config["general"]["cluster_algorithm"],
            "distance_metric": "manhattan", "use_medioids": False, "use_means": True,
            "layer": "scaled", "show_duplicates": False, "show_classes": False}
    config["to_plot"]["down"]["heatmaps"]["DEG_params"] = {
            "top_n_genes": 20, "perc": .2, "p_val_cutoff": 1e-5, "lfc": 1,
            "overlap_fill_to_top_n": False, "direction": "up_n_down"}
    # ############################################################################################
    # The Analysis CSVs to create
    # save the DEGs as csvs
    config["to_create"]["down"]["DEG_csv"]["create"] = True
    # save the marker dicts as csvs
    config["to_create"]["down"]["marker_csv"]["create"] = True
    # Modalitys to plot paralelle mean the clusters are horizontally added to the csv
    config["to_create"]["down"]["DEG_csv"]["marker_mod"] = ["rna"]  # ["rna", "prot", "comb"]
    config["to_create"]["down"]["DEG_csv"]["n_genes"] = 100
    # Split the CSVs into per cluster
    config["to_create"]["down"]["DEG_csv"]["one_csv_per_cluster"] = True
    # Number of genes to take for the parallel csv
    config["to_create"]["down"]["DEG_csv"]["marker_mod_parallel"] = []  # ["rna", "prot", "comb"]
    config["to_create"]["down"]["DEG_csv"]["parallel_n_genes"] = 200
    config["to_create"]["down"]["DEG_csv"]["pval_cutoff"] = 0.05
    config["to_create"]["down"]["DEG_csv"]["log2fc_min"] = .5
    config["to_create"]["down"]["DEG_csv"]["pct_min"] = .1  # TODO: implement the subsetting by percentage
    # ############################################################################################
    # save the clustering stats as csvs
    config["to_create"]["down"]["cluster_stats_csv"]["create"] = True
    config["to_create"]["down"]["cluster_stats_csv"]["marker_mod"] = ["rna"]  # ["rna", "prot", "comb"]
    # ##################################################################################################
    # Define the parameters for the default scannpy functions:
    # Setup default scanpys pp
    config["pp"] = {
            "calculate_qc_metrics": {
                "percent_top": None, "layer": None, "use_raw": False,
                "inplace": True, "log1p": False,
                },
            "filter_cells": {"inplace": True},
            "filter_genes": {"inplace": True},
            "filter_qc_var_obs": {},
            "filter_qc_var_var": {},
            "highly_variable_genes": {
                    "layer": "norm_counts", "n_top_genes": 5000, "span": 1., "n_bins": 20,
                    "flavor": "ours", "subset": False, "inplace": True, "batch_key": None,
                    "check_values": False},
            "log1p": {
                    "base": None, "copy": False, "chunked": None, "chunk_size": None,
                    "layer": None, "obsm": None},
            "pca": {
                    "n_comps": None, "zero_center": True, "svd_solver": "arpack",
                    "random_state": config["general"]["seed"],
                    "return_info": False, "use_highly_variable": False, "dtype": "float64",
                    "copy": False, "chunked": False, "chunk_size": None,
                    "method": "pca" if not use_GPU else "rapids"},
            "normalize_total": {
                    "target_sum": None, "exclude_highly_expressed": False,
                    "key_added": None, "layer": None, "layers": None, "layer_norm": None, "inplace": True,
                    "copy": False},
            "regress_out": {
                    "keys": ["n_counts", "pct_MT"],
                    "n_jobs": config["general"]["n_cores"], "copy": False},
            "scale": {
                     "zero_center": True, "max_value": 10, "copy": False},
            # NOTE: The layer and obsm of scale are buggy, so this is not added: "layer": None, "obsm": None},
            "subsample": {
                    "fraction": None, "n_obs": None, "random_state": config["general"]["seed"], "copy": False},
            "neighbors": {
                    "n_neighbors": 20, "n_pcs": 5000, "use_rep": "X_pca", "knn": True,
                    "random_state": config["general"]["seed"],
                    "method": "umap",
                    "transformer": "sklearn" if not use_GPU else "rapids",
                    "metric": "euclidean",
                    "key_added": None, "copy": False}}
    # #############################################
    # Setup default scanpys tl
    # TODO: add all the usefull parameters to the dictionaries
    config["tl"] = {
            "pca": config["pp"]["pca"],
            "tsne": {
                "use_raw": False,
                "n_pcs": None, "use_rep": None, "perplexity": 30, "early_exaggeration": 12,
                "learning_rate": 1000, "random_state": config["general"]["seed"], "use_fast_tsne": False,
                "n_jobs": config["general"]["n_cores"], "copy": False,  "metric": 'euclidean',
                "method": "pca" if not use_GPU else "rapids",
                },
            "umap": {
                "min_dist": 0.5, "spread": 1.0, "n_components": 2, "maxiter": None,
                "alpha": 1.0, "gamma": 1.0, "negative_sample_rate": 5, "init_pos": 'spectral',
                "random_state": config["general"]["seed"], "a": None, "b": None, "copy": False,
                "method": "umap" if not use_GPU else "rapids", "neighbors_key": None,
                },
            "draw_graph": {
                "use_raw": False,
                "layout": 'fa', "init_pos": None, "root": None, "random_state": config["general"]["seed"],
                "n_jobs": config["general"]["n_cores"], "adjacency": None, "key_added_ext": None,
                "neighbors_key": None, "obsp": None, "copy": False,
                },
            "diffmap": {
                "use_raw": False,
                "n_comps": 15, "neighbors_key": None, "random_state": config["general"]["seed"],
                "copy": False,
                },
            "embedding_density": {
                "use_raw": False,
                "basis": 'umap', "groupby": None, "key_added": None, "components": None,
                },
            "leiden": {
                "resolution": .75,  "restrict_to": None, "random_state": config["general"]["seed"],
                "key_added": 'leiden', "adjacency": None, "directed": True, "use_weights": True,
                "n_iterations": -1, "partition_type": None, "neighbors_key": None, "obsp": None,
                "copy": False, "flavor": 'leidenalg', "method": "leiden" if not use_GPU else "rapids",
                },
            "dendrogram": {
                "n_pcs": None, "use_rep": None, "var_names": None, "use_raw": False,
                "cor_method": 'kendall', "linkage_method": 'complete',
                "optimal_ordering": False, "key_added": None, "inplace": True,
                },
            "rank_genes_groups": {
                "use_raw": False, "groups": 'all', "reference": 'rest', "n_genes": None,
                "rankby_abs": True, "pts": True, "key_added": None, "copy": False,
                "method": "wilcoxon", "corr_method": 'benjamini-hochberg', "tie_correct": True,
                "layer": None,
                },
            "filter_rank_genes_groups": {
                 "key": None, "groupby": None, "use_raw": False, "key_added": 'rank_genes_groups_filtered',
                 "min_in_group_fraction": 0.25, "min_fold_change": 1, "max_out_group_fraction": 0.5,
                 "compare_abs": False,
                },
            "marker_gene_overlap": {
                "key": 'rank_genes_groups', "method": 'overlap_count', "normalize": None,
                "top_n_markers": None, "adj_pval_threshold": None,
                "key_added": 'marker_gene_overlap', "inplace": False
                },
            "score_genes": {
                "use_raw": False, "n_bins": 25
                },
            "score_genes_cell_cycle": {"copy": False},
            "dpt": {
                "n_dcs": 10, "n_branchings": 0, "min_group_size": 0.01,
                "allow_kendall_tau_shift": True, "neighbors_key": None, "copy": False,
                },
            "paga": {
                "groups": None, "use_rna_velocity": False, "model": 'v1.2', "neighbors_key": None, "copy": False}}
    # #############################################
    # Setup default plotting Parameters
    config["pl"] = {
        "scatter": {
                "show": config["general"]["show_plots"],
                },
        "heatmap": {
                "show": config["general"]["show_plots"],
                "use_raw": False, "log": False, "num_categories": 7, "dendrogram": False,
                "gene_symbols": None, "var_group_positions": None, "var_group_labels": None,
                "var_group_rotation": None, "layer": None, "standard_scale": None,  # "var",
                "swap_axes": False, "show_gene_labels": None,
                "figsize": None, "vmin": None, "vmax": None,
                "vcenter": None, "norm": None, "cmap": cmap,
                },
        "dotplot": {
                "show": config["general"]["show_plots"],
                "use_raw": False, "log": False, "num_categories": 7, "expression_cutoff": 0.0,
                "mean_only_expressed": False, "cmap": cmap, "dot_max": None, "dot_min": None,
                "standard_scale": None, "smallest_dot": 0.0, "title": None,
                "colorbar_title": 'Mean expression\nin group',
                "size_title": 'Fraction of cells\nin group (%)',
                "figsize": None, "dendrogram": True, "gene_symbols": None, "var_group_positions": None,
                "var_group_labels": None, "var_group_rotation": None, "layer": None, "swap_axes": False,
                "dot_color_df": None, "return_fig": False, "vmin": None,
                "vmax": None, "vcenter": None, "norm": None
                },
        "tracksplot": {
                "show": config["general"]["show_plots"],
                "use_raw": False, "log": False, "dendrogram": False, "gene_symbols": None,
                "var_group_positions": None, "var_group_labels": None, "layer": None,
                "figsize": None,
                },
        "violin": {
                "show": config["general"]["show_plots"],
                "groupby": None, "log": False, "use_raw": False, "stripplot": True, "jitter": True,
                "size": 1, "layer": None, "scale": 'width', "order": None, "multi_panel": None,
                "xlabel": '', "ylabel": None, "rotation": 90,
                },
        "stacked_violin": {
                "show": config["general"]["show_plots"],
                "log": False, "use_raw": False, "num_categories": 7, "title": None,
                "colorbar_title": 'Median expression\nin group', "figsize": None,
                "dendrogram": False, "gene_symbols": None, "var_group_positions": None,
                "var_group_labels": None, "standard_scale": None, "var_group_rotation": None,
                "layer": None, "stripplot": False, "jitter": False, "size": 1, "scale": 'width',
                "yticklabels": False, "order": None, "swap_axes": False,  "save": None,
                "return_fig": False, "row_palette": None, "cmap": 'Blues',
                "vmin": None, "vmax": None, "vcenter": None, "norm": None,
                },
        "matrixplot": {
                "show": config["general"]["show_plots"],
                "use_raw": False, "log": False, "num_categories": 7, "figsize": None,
                "dendrogram": False, "title": None, "cmap": cmap,
                "colorbar_title": 'Mean expression\nin group', "gene_symbols": None,
                "var_group_positions": None, "var_group_labels": None, "var_group_rotation": None,
                "layer": None, "standard_scale": None, "values_df": None, "swap_axes": False,
                "return_fig": False, "vmin": None, "vmax": None,
                "vcenter": None, "norm": None,
                },
        "clustermap": {
                "show": config["general"]["show_plots"],
                "obs_keys": None, "use_raw": False,  "save": None,
                },
        "ranking": {
                "show": config["general"]["show_plots"],
                "dictionary": None, "indices": None, "labels": None, "color": 'black', "n_points": 30,
                "log": False, "include_lowest": False,
                },
        "dendrogram": {
                "show": config["general"]["show_plots"],
                "dendrogram_key": None, "orientation": 'top', "remove_labels": False,
                },
        "highest_expr_genes": {
                "show": config["general"]["show_plots"],
                "n_top": 30,  "gene_symbols": None, "log": False,
                },
        "filter_genes_dispersion": {
                "show": config["general"]["show_plots"],
                "log": False,  "save": None,
                },
        "highly_variable_genes": {
                "show": config["general"]["show_plots"],
                "log": False,  "highly_variable_genes": True,
                },
        "pca_variance_ratio": {
                "show": config["general"]["show_plots"],
                "log": True, "n_pcs": 30, "save": None,
                },
        "pca": {
                "show": config["general"]["show_plots"],
                "color": None, "gene_symbols": None, "use_raw": False, "sort_order": True,
                "edges": False, "edges_width": 0.1, "edges_color": 'grey', "neighbors_key": None,
                "arrows": False, "arrows_kwds": None, "groups": None, "components": None,
                "dimensions": None, "layer": None, "projection": '2d', "scale_factor": None,
                "color_map": None, "cmap": cmap, "palette": None, "na_color": 'lightgray',
                "na_in_legend": True, "size": None, "frameon": None, "legend_fontsize": None,
                "legend_fontweight": 'bold', "legend_loc": 'right margin', "legend_fontoutline": None,
                "colorbar_loc": 'right', "vmax": None, "vmin": None, "vcenter": None, "norm": None,
                "add_outline": False, "outline_width": [0.3, 0.05],
                "outline_color": ['black', 'white'], "ncols": 4, "hspace": 0.25, "wspace": None,
                "title": None,  "return_fig": None, "annotate_var_explained": False,
                },
        "pca_loadings": {
                "show": config["general"]["show_plots"],
                "components": None, "include_lowest": True, "n_points": None,  "save": None,
                },
        "tsne": {
                "show": config["general"]["show_plots"],
                "color": None, "gene_symbols": None, "use_raw": False, "sort_order": True,
                "edges": False, "edges_width": 0.1, "edges_color": 'grey', "neighbors_key": None,
                "arrows": False, "arrows_kwds": None, "groups": None, "components": None, "dimensions": None,
                "layer": None, "projection": '2d', "scale_factor": None, "color_map": None, "cmap": None,
                "palette": None, "na_color": 'lightgray', "na_in_legend": True, "size": None, "frameon": None,
                "legend_fontsize": None, "legend_fontweight": 'bold', "legend_loc": 'right margin',
                "legend_fontoutline": None, "colorbar_loc": 'right', "vmax": None, "vmin": None, "vcenter": None,
                "norm": None, "add_outline": False, "outline_width": [0.3, 0.05], "outline_color": ['black', 'white'],
                "ncols": 4, "hspace": 0.25, "wspace": None, "title": None,  "return_fig": None,
                },
        "umap": {
                "show": config["general"]["show_plots"],
                "gene_symbols": None, "use_raw": False, "sort_order": True,
                "edges": False, "edges_width": 0.1, "edges_color": 'grey', "neighbors_key": None,
                "arrows": False, "arrows_kwds": None, "groups": None, "components": None,
                "dimensions": None, "layer": None, "projection": '2d', "scale_factor": None,
                "color_map": None, "cmap": cmap, "palette": None, "na_color": 'lightgray',
                "na_in_legend": True, "size": None, "frameon": None, "legend_fontsize": None,
                "legend_fontweight": 'bold', "legend_loc": 'right margin', "legend_fontoutline": None,
                "colorbar_loc": 'right', "vmax": None, "vmin": None, "vcenter": None, "norm": None,
                "add_outline": False, "outline_width": [0.3, 0.05], "outline_color": ['black', 'white'],
                "ncols": 4, "hspace": 0.25, "wspace": None, "title": None,  "ax": None,
                "return_fig": None,
                },
        "diffmap": {
                "show": config["general"]["show_plots"],
                "color": None, "gene_symbols": None, "use_raw": False, "sort_order": True,
                "edges": False, "edges_width": 0.1, "edges_color": 'grey', "neighbors_key": None,
                "arrows": False, "arrows_kwds": None, "groups": None, "components": None,
                "dimensions": None, "layer": None, "projection": '2d', "scale_factor": None,
                "color_map": None, "cmap": None, "palette": None, "na_color": 'lightgray',
                "na_in_legend": True, "size": None, "frameon": None, "legend_fontsize": None,
                "legend_fontweight": 'bold', "legend_loc": 'right margin', "legend_fontoutline": None,
                "colorbar_loc": 'right', "vmax": None, "vmin": None, "vcenter": None, "norm": None,
                "add_outline": False, "outline_width": [0.3, 0.05], "outline_color": ['black', 'white'],
                "ncols": 4, "hspace": 0.25, "wspace": None, "title": None,  "ax": None,
                "return_fig": None,
                },
        "draw_graph": {
                "show": config["general"]["show_plots"],
                "color": None, "gene_symbols": None, "use_raw": False, "sort_order": True,
                "edges": False, "edges_width": 0.1, "edges_color": 'grey', "neighbors_key": None,
                "arrows": False, "arrows_kwds": None, "groups": None, "components": None,
                "dimensions": None, "layer": None, "projection": '2d', "scale_factor": None,
                "color_map": None, "cmap": None, "palette": None, "na_color": 'lightgray',
                "na_in_legend": True, "size": None, "frameon": None, "legend_fontsize": None,
                "legend_fontweight": 'bold', "legend_loc": 'right margin', "legend_fontoutline": None,
                "colorbar_loc": 'right', "vmax": None, "vmin": None, "vcenter": None, "norm": None,
                "add_outline": False, "outline_width": [0.3, 0.05], "outline_color": ['black', 'white'],
                "ncols": 4, "hspace": 0.25, "wspace": None, "title": None,  "ax": None,
                "return_fig": None, "layout": None,
                },
        "spatial": {
                "show": config["general"]["show_plots"],
                "color": None, "gene_symbols": None, "use_raw": False, "sort_order": True,
                "edges": False, "edges_width": 0.1, "edges_color": 'grey', "neighbors_key": None,
                "arrows": False, "arrows_kwds": None, "groups": None, "components": None,
                "dimensions": None, "layer": None, "projection": '2d', "scale_factor": None,
                "color_map": None, "cmap": None, "palette": None, "na_color": None,
                "na_in_legend": True, "size": 1.0, "frameon": None, "legend_fontsize": None,
                "legend_fontweight": 'bold', "legend_loc": 'right margin', "legend_fontoutline": None,
                "colorbar_loc": 'right', "vmax": None, "vmin": None, "vcenter": None, "norm": None,
                "add_outline": False, "outline_width": [0.3, 0.05], "outline_color": ['black', 'white'],
                "ncols": 4, "hspace": 0.25, "wspace": None, "title": None,  "ax": None,
                "return_fig": None, "basis": 'spatial', "img": None,
                "crop_coord": None, "alpha_img": 1.0, "bw": False, "spot_size": None,
                },
        "embedding": {
                "show": config["general"]["show_plots"],
                "color": None, "gene_symbols": None, "use_raw": False, "sort_order": True, "edges": False,
                "edges_width": 0.1, "edges_color": 'grey', "neighbors_key": None, "arrows": False,
                "arrows_kwds": None, "groups": None, "components": None, "dimensions": None,
                "layer": None, "projection": '2d', "scale_factor": None, "color_map": None,
                "cmap": None, "palette": None, "na_color": 'lightgray', "na_in_legend": True,
                "size": None, "frameon": None, "legend_fontsize": None, "legend_fontweight": 'bold',
                "legend_loc": 'right margin', "legend_fontoutline": None, "colorbar_loc": 'right',
                "vmax": None, "vmin": None, "vcenter": None, "norm": None, "add_outline": False,
                "outline_width": [0.3, 0.05], "outline_color": ['black', 'white'], "ncols": 4,
                "hspace": 0.25, "wspace": None, "title": None,  "return_fig": None,
                },
        "rank_genes_groups": {
                "show": config["general"]["show_plots"],
                "groups": None, "n_genes": 25, "gene_symbols": None, "key": 'rank_genes_groups',
                "fontsize": 8, "ncols": 4, "sharey": True,  "ax": None,
                },
        "rank_genes_groups_violin": {
                "show": config["general"]["show_plots"],
                "groups": None, "n_genes": 30, "gene_symbols": None, "key": 'rank_genes_groups',
                "fontsize": 8, "ncols": 4, "sharey": True,  "jitter": False,
                },
        "rank_genes_groups_stacked_violin": {
                "show": config["general"]["show_plots"],
                "groups": None, "n_genes": None, "groupby": None, "gene_symbols": None,
                "var_names": None, "min_logfoldchange": None, "key": None,  "save": None,
                "return_fig": False,
                },
        "rank_genes_groups_heatmap": {
                "show": config["general"]["show_plots"],
                "groups": None, "n_genes": None, "groupby": None, "gene_symbols": None,
                "var_names": None, "min_logfoldchange": None, "key": None,  "save": None,
                },
        "rank_genes_groups_dotplot": {
                "show": config["general"]["show_plots"],
                "groups": None, "n_genes": None, "groupby": None, "values_to_plot": None,
                "var_names": None, "gene_symbols": None, "min_logfoldchange": None, "key": None,
                "return_fig": False,
                },
        "rank_genes_groups_matrixplot": {
                "show": config["general"]["show_plots"],
                "groups": None, "n_genes": None, "groupby": None, "values_to_plot": None,
                "var_names": None, "gene_symbols": None, "min_logfoldchange": None, "key": None,  "return_fig": False,
                },
        "rank_genes_groups_tracksplot": {
                "show": config["general"]["show_plots"],
                "groups": None, "n_genes": None, "groupby": None, "var_names": None, "gene_symbols": None,
                "min_logfoldchange": None, "key": None,  "save": None}}
    # ############################################################################################
    config["dc"] = {
                "run_type": "aucell", "db": "Custom", "markers_only": "",
                "visualize": False, "marker_dict": None, "weight": None, "methods": None, "databases": None,
                "append_celltype": False, "path_to_data": "./databases/", "umap_dot_size": 4,
                "replacement_dict": None, "all_celltypes_to_use": None, "try_automatic_grouping": False,
                "include_markers_in_all_celltypes": False, "palette": None, "min_n": 0,
                "layer": "log2norm_counts", "use_raw": False, "add_to_obs": False, "groupby_leiden": False}
    config["sc_api"] = {}
    # #################################################################################################################
    # THINGS YOU SHOULD NOT CHANGE!!!!! (Unless you talked to Christopher or Tested it carefully)
    # ###############################################################
    # Default key setup
    config["general"]["sample_n_condition_keys"] = sample_key
    config["general"]["mitochondiral_key"] = mitochondiral_key
    config["general"]["ribosomal_key"] = ribosomal_key
    config["general"]["mito_ribosomal_key"] = mito_ribosomal_key
    config["general"]["pseudogene_key"] = pseudogene_key
    config["general"]["house_keeping_key"] = house_keeping_key
    config["general"]["hemoglobin_key"] = hemoglobin_key
    # ###############################################################
    if config["general"]["organism"] in ["human", "mouse"]:
        # ##############################################################
        # Load the genesets from file
        for name_, f in GENESET_FILENAMES["PATH_TO_QC_GENESETS"][config["general"]["organism"]].items():
            # print(config["general"]["organism"])
            abs_path = ALL_PATHS["PATH_TO_DATABASE"] + f
            # Check if file exists, if somebody is so smart and chage it manually and not in the paths.py -.-
            if os.path.exists(abs_path):
                update_dict = {f'{name_}_{k}': v for k, v in dataset_to_dict(abs_path).items()}
                config["qc"]["gene_identifiers"].update(
                    update_dict)
            else:
                logger.info(f'Path not found, please check if:\n {ALL_PATHS["PATH_TO_DATABASE"]}\n' /
                            f'contains the files:\n{f}')
        # ##############################################################
        # Add Manually the necessary non database driven genes
        if config["general"]["organism"] == "human":
            # #######################
            if config["general"]["mitochondiral_key"] in config["qc"]["gene_identifiers"]:
                config["qc"]["gene_identifiers"][config["general"]["mitochondiral_key"]] = (
                    config["qc"]["gene_identifiers"][config["general"]["mitochondiral_key"]] + "|^MT-")
            else:
                config["qc"]["gene_identifiers"][config["general"]["mitochondiral_key"]] = "^MT-"
            # #######################
            config["qc"]["gene_identifiers"][config["general"]["mito_ribosomal_key"]] = r"^MRPL\d|^MRPS\d"
            config["qc"]["gene_identifiers"][config["general"]["pseudogene_key"]] = (
                    r"^AC[\d]+\.[\d]+|^AL[\d]+\.[\d]+|^AP[\d]+\.[\d]+")
            # FROM: https://www.ncbi.nlm.nih.gov/datasets/gene/taxon/9606/?search=hemoglob
            # FROM: https://www.ncbi.nlm.nih.gov/datasets/gene/GCF_000001405.40/?search=hemoglo
            config["qc"]["gene_identifiers"][config["general"]["hemoglobin_key"]] = (
                    "|".join([
                        '^HBA1$', '^HBA2$', '^HBB$', '^HBD$', '^HBE1$', '^HBG1$',
                        '^HBG2$', '^HBM$', '^HBQ1$', '^HBZ$', '^AHSP$', '^LOC106804612$',
                        '^LOC106804613$', '^LOC110011217$', '^LOC110008579$', '^HBAP1$', '^HBBP1$',
                        '^HBZP1$', '^RHEX$', '^LOC110013311$']))
        elif config["general"]["organism"] == "mouse":
            if config["general"]["mitochondiral_key"] in config["qc"]["gene_identifiers"]:
                config["qc"]["gene_identifiers"][config["general"]["mitochondiral_key"]] = (
                    config["qc"]["gene_identifiers"][config["general"]["mitochondiral_key"]] + "|^Mt-|mt-")
            else:
                config["qc"]["gene_identifiers"][config["general"]["mitochondiral_key"]] = "^Mt-|mt-"
            config["qc"]["gene_identifiers"][config["general"]["ribosomal_key"]] = (
                    r"^(Rps\d+$|Rpl\d+$|Rpsa$|Rplp\d+$|Uba52$|Dap3$|Fau$)")
            # FROM: https://www.ncbi.nlm.nih.gov/datasets/gene/GCF_000001635.27/?search=hemoglo
            config["qc"]["gene_identifiers"][config["general"]["hemoglobin_key"]] = (
                    "|".join([
                        '^Hbb-bt$', '^Hbb-bs$', '^Hbb-bh3$', '^Hbb-bh2$', '^Hbb-bh2$', '^Hbb-bh2$', '^Hba-ps4$'
                        '^Ahsp$', '^Hba-x$', '^Hba-a1$', '^Hbq1b$', '^Hba-a2$', '^Hbq1a$', '^Hba-ps3$']))
        # ##############################################################
        config["pp"]["calculate_qc_metrics"]["qc_vars"] = [*list(config["qc"]["gene_identifiers"].keys())]

    else:
        # TODO: Implement non Human geene sets
        raise NotImplementedError("The usage of non human or mouse is not implemented yet, please do it!")
    # #############################################
    # Use GPU functionality, don't change it here, use the use_GPU argument for the function call.
    if use_GPU:
        config["general"]["use_GPU"] = True
    else:
        config["general"]["use_GPU"] = False
        logger.info(
                "NOTE: GPU processing starts with the Clustering "
                "CPU functionality may not be completely implemented yet.")
    # #############################################
    # DEPRECATED
    config["scToolkit"]["hist_eq_divisor"] = 2
    # #############################################
    return config


def dataset_to_dict(
            path: str,
            exclude_reference: bool = True,
            return_regex: bool = False,
        ) -> dict[str, list[str]]:
    """Creates a CSV of columns of genes to a dictionary.

    NOTE:
        - this will exclude the column "reference" because we use it to list the
          papers to cite for each column!
        - CSV stands for COMMA separeted, no excel or tab or whatever separated!

    Args:
        path (str): Path to the CSV
        exclude_reference (bool, optional): If you want to not exclude a colum
            named "reference", use at your own risk. Defaults to True.

    Returns:
        dict[str, list[str]]:
            dict[str, list[str]]

    Called By:
        get_config

    Tags:
        annotation, io
    """
    dict_ = {}
    genesets = pd.read_csv(path)
    if exclude_reference:
        genesets = genesets[[k for k in genesets.columns if k != "references"]]
    for gs_name in genesets.keys():
        if return_regex:
            dict_[gs_name] = "$|^".join(
                    [g.replace(" ", "").replace(".", "/.")
                        for g in genesets[gs_name].dropna()])
            dict_[gs_name] = "^" + dict_[gs_name][1:-1] + "$"
        else:
            dict_[gs_name] = genesets[gs_name].dropna().tolist()
    return dict_


def get_stats() -> dict:
    """
    Returns a statistics dictionary for saving filtering,
    gene exclusions and exections.

    "preprocessors_ran" is for steps that should not be executed twice.

    Returns:
        dict:
            Statistics dictionary for saving in the adata.uns["stats"]

    Called By:
        setup_adata

    TODO:
        Implement more functionality for saving the processing steps

    Tags:
        stats
    """
    stats = {"preprocessors_ran": [],
             "pre_clustering_gene_exclustion": []}

    return stats


# ###########################################################################################################
# GPU handling
def change_gpu_usage(
            adata: object,
            enable: bool = True,
            to_enable: list[str] = ["general", "pca", "leiden", "neighbors", "umap"]
        ) -> None:
    """
    Enables or disables GPU support globally or for specific operations in
    an adata object.

    to_enable=["global"], enable=False, would be global disabling
    to_enable=["global"], enable=True, would NOT be global enabling.
    therefore you have to use to_enable=["general", "pca", "leiden", "neighbors", "umap"]

    This function modifies the configuration settings in ``adata.uns`` to enable
    or disable GPU acceleration for selected preprocessing and analysis methods,
    including PCA, Leiden clustering, neighbor graph construction, and UMAP.

    NOTE:
        This function assumes that ``adata.uns["config"]`` follows a specific
        hierarchical structure with keys for preprocessing (``pp``) and tools
        (``tl``). Ensure that this structure exists before calling this function.

    Args:
        adata (object): adata object containing configuration settings in
            ``adata.uns``.
        enable (bool, optional): Whether to enable (True) or disable (False) GPU
            support. Defaults to True.
        to_enable (list[str], optional): List of operations to modify. Supported
            options are "pca", "leiden", "neighbors", and "umap".
            Defaults to ["pca", "leiden", "neighbors", "umap"].

    Returns:
        None

    Tags:
        config
    """
    # #########################################################
    # Set general GPU usage flag in the configuration
    if "general" in to_enable:
        adata.uns["config"]["general"]["use_GPU"] = "True" if enable else "False"
    # #########################################################
    # Configure GPU acceleration for individual components
    # ##########################################
    # Configure PCA computation method
    if "pca" in to_enable:
        adata.uns["config"]["pp"]["pca"]["method"] = "rapids" if enable else "pca"
    # ##########################################
    # Configure Leiden clustering method
    if "leiden" in to_enable:
        adata.uns["config"]["tl"]["umap"]["method"] = "rapids" if enable else "umap"
    # ##########################################
    # Configure nearest neighbors computation method
    if "neighbors" in to_enable:
        adata.uns["config"]["tl"]["leiden"]["method"] = "rapids" if enable else "leiden"
    # ##########################################
    # Configure UMAP embedding method
    if "umap" in to_enable:
        adata.uns["config"]["pp"]["neighbors"]["transformer"] = "rapids" if enable else "sklearn"


# ###########################################################################################################
# Nested dicts /experiment dict handlings
def search_regex_nested_dict_list(
            collection: experiment_dict | dict | list | str,
            pattern: str,
            path: str = "",
            sep: str = '"]["',
            start: str = '["',
            end: str = '"]',
        ) -> None:
    """
    Recursively searches a dictionary or list for keys or values matching a
    regex pattern and prints their paths/access.

    This function navigates through nested dictionaries or lists, looking for
    keys or values that match the provided regular expression pattern. When a
    match is found, the function prints the path leading to that key or value.
    The path is a string representation showing the hierarchy of keys or indices
    leading to the matched element.

    NOTE:
        The function assumes that the data structure is a combination of
        dictionaries and lists and that the path is represented by a string with
        keys or indices separated by the '|' character.

    Args:
        collection (scToolkit.experiment_dict, dict, list or str):
            The dictionary or list to search through.
            The str option is for internal use.
        pattern (str): The regular expression pattern to match against keys or
            values.
        path (str, optional): The current path in the dictionary or list, used
            during recursion to track the hierarchy. Defaults to "".
        sep (str, optional): The delimiter used to split the string lists.
            Defaults to '"]["'.
        start (str, optional): The delimiter used to split the string lists.
            Defaults to '["'.
        end (str, optional): The delimiter used to split the string lists.
            Defaults to '"]'.

    Returns:
        None:
            This function does not return a value. Instead, it prints out the
            paths of matched keys or values.

    Raises:
        None: This function does not raise any exceptions explicitly.

    Calls:
        search_regex_nested_dict_list

    Called By:
        search_regex_nested_dict_list, search_scToolkit_function_legacy

    TODO:
        Consider adding an option to return the paths as a list instead of
        printing them.

    Tags:
        utils
    """
    # #########################################################
    # Compile the regex pattern for matching against keys or values
    regex = compile(pattern)
    # #########################################################
    # Check if the input is a dictionary
    if isinstance(collection, (dict, experiment_dict)):
        # ##########################################
        # Iterate through each key-value pair in the dictionary
        for key, value in collection.items():
            # Generate a new path string by appending the current key
            if path:
                new_path = f'{path}{sep}{key}'
            else:
                new_path = f'{start}{key}'
            # ##########################################
            # If the key matches the regex pattern, print the path
            if regex.search(str(key)):
                logger.info(new_path + end)
            # Recursively search within the value associated with the current key
            search_regex_nested_dict_list(
                value, pattern, new_path, sep, start, end)
    # #########################################################
    # Check if the input is a list
    elif isinstance(collection, list):
        # ##########################################
        # Iterate through each item in the list
        for item in collection:
            # Recursively search within the current list item
            search_regex_nested_dict_list(
                item, pattern, path, sep, start, end)
    # #########################################################
    # Handle the case where the input is neither a dictionary nor a list
    elif isinstance(collection, (str, int, float)) or collection is None:
        # ##########################################
        # If the value matches the regex pattern, print the path includings the value
        if regex.search(str(collection)):
            logger.info(f'{start}{path}{sep}{collection}{end}')
    else:
        print(collection, type(collection))
        # ##########################################
        raise TypeError(
            f"Expected dict or list, got {type(collection).__name__}")
        # If the value matches the regex pattern, print the path includings the value
        # if regex.search(str(collection)):
        #     logger.info(f'{start}{path}{sep}{collection}{end}')


def search_scToolkit_function_legacy(
            regex: str
        ) -> None:
    """
    Searches for a given regular expression pattern within a nested dictionary
    list structure generated by ``create_code_structure()`` and performs a regex search.

    This function is designed to help locate specific patterns within a
    potentially large and complex nested structure, which is commonly found in
    Scanpy's API documentation or similar resources.

    NOTE:
        If the interpreter tells you the function is not available, use
        search_scToolkit_function_legacy("function_name")
        and it will show you the list of posible available modules having
        this function. just change the old_module.function to
        new_module.function and it should do the trick ;)

    Args:
        regex (str): A regular expression pattern to search within the nested
            dictionary list structure.

    Returns:
        None:
            This function performs the search operation but does not return
            any value.

    Raises:
        ValueError: If the provided regex is not a valid regular expression
            pattern.
        TypeError: If the input is not a string.

    Calls:
        create_code_structure, search_regex_nested_dict_list

    TODO:
        Implement error handling for cases where ``create_code_structure()``
        returns an unexpected data format.

    Tags:
        codebase
    """
    # #########################################################
    # Generate the nested dictionary list structure
    # This structure is typically used to represent the API's code structure
    code_structure = create_code_structure()
    # #########################################################
    # Perform the regex search within the generated structure
    # The search is done by the function ``search_regex_nested_dict_list``
    search_regex_nested_dict_list(code_structure, regex,
                                  sep=".", start="", end="")


def update_nested_dict(
            nested_dict: dict,
            nested_dict_update: dict
        ) -> dict:
    """Updates a nested dictionary with values from another nested dictionary.

    This function recursively updates a nested dictionary ``nested_dict`` with the
    values from another nested dictionary ``nested_dict_update``. If the same key
    exists in both dictionaries and the value associated with that key is also a
    dictionary, it will merge the dictionaries rather than overwriting. This
    allows for deep merging of nested dictionaries.

    NOTE:
        This function is similar to dict.update(other_dict), but it supports
        nested dictionaries.

    Example use case:
        Consider a scenario where you have a default configuration dictionary
        and you want to update it with user-specified overrides, while
        preserving the nested structure.

    Args:
        nested_dict (dict): The dictionary to update. This is the dictionary
            that will be modified.
        nested_dict_update (dict): The dictionary where the update comes from.
            This contains the new values that will be merged into ``nested_dict``.

    Returns:
        dict:
            The updated dictionary with the merged values from
            ``nested_dict_update``.

    References:
        https://stackoverflow.com/questions/3232943/update-value-of-a-nested-dictionary-of-varying-depth

    Calls:
        update_nested_dict

    Called By:
        load_h5ad_old, update_nested_dict

    Tags:
        utils
    """
    # #########################################################
    # Iterate through the items of nested_dict_update to merge into nested_dict
    for k, v in nested_dict_update.items():
        # ##########################################
        # Check if the value is a mapping to handle nested dictionaries
        if isinstance(v, Mapping):
            # Recursively update the nested dictionary
            nested_dict[k] = update_nested_dict(nested_dict.get(k, {}), v)
        else:
            # ##########################################
            # Update the key with the new value if it's not a mapping
            nested_dict[k] = v
    # #########################################################
    # Return the updated dictionary
    return nested_dict


def update_nested(
            base: dict | list,
            updates: dict | list
        ) -> None:
    """
    Recursively updates a nested dictionary or list structure with values from
    another dictionary or list.

    This function modifies the ``base`` structure in place by merging values from
    ``updates``. If both ``base`` and ``updates`` contain dictionaries, they are
    recursively merged. If they contain lists, corresponding elements are
    updated where possible. If the index in ``updates`` exceeds the length of
    ``base``, the new elements are appended.

    NOTE:
        - The function modifies the ``base`` object in place and does not return a
          new structure.
        - If ``updates`` contains new keys or indices, they are added to ``base``.
        - Lists are updated by modifying their corresponding elements or
          appending new ones.

    Args:
        base (dict | list): The original dictionary or list to be updated.
        updates (dict | list): The dictionary or list containing updates.

    Returns:
        None

    Raises:
        TypeError: If either ``base`` or ``updates`` is not a dictionary or a list.

    Calls:
        update_nested

    Called By:
        update_nested

    Tags:
        utils
    """
    # #########################################################
    # Ensure ``base`` and ``updates`` are both valid dictionary or list structures
    if not isinstance(base, (dict, list)) or not isinstance(updates, (dict, list)):
        raise TypeError("Both ``base`` and ``updates`` must be either a dictionary or a list.")
    # #########################################################
    # Handle dictionary-based recursive updates
    if isinstance(base, dict) and isinstance(updates, dict):
        for k, v in updates.items():
            if k in base:
                # ##########################################
                # If both values are dictionaries, merge recursively
                if isinstance(base[k], dict) and isinstance(v, dict):
                    update_nested(base[k], v)
                # If both values are lists, merge recursively
                elif isinstance(base[k], list) and isinstance(v, list):
                    update_nested(base[k], v)
                # Otherwise, overwrite the existing value
                else:
                    base[k] = v
            else:
                # ##########################################
                # If the key is not present in ``base``, add it
                base[k] = v
    # #########################################################
    # Handle list-based recursive updates
    elif isinstance(base, list) and isinstance(updates, list):
        for i, item in enumerate(updates):
            if i < len(base):
                # ##########################################
                # If both values are dictionaries, merge recursively
                if isinstance(base[i], dict) and isinstance(item, dict):
                    update_nested(base[i], item)
                # If both values are lists, merge recursively
                elif isinstance(base[i], list) and isinstance(item, list):
                    update_nested(base[i], item)
                # Otherwise, overwrite the existing value
                else:
                    base[i] = item
            else:
                # ##########################################
                # Append new elements if the list index exceeds ``base``
                base.append(item)


def get_nested_dict_keys_structure(
            dict_: dict
        ) -> dict:
    """Recursively extracts the key structure of a nested dictionary.

    Use-Case: For exploring the experiment_dict config like
        get_nested_dict_keys_structure(config["general"])

    Args:
        dict_ (dict): The dictionary whose key structure should be extracted.

    Returns:
        dict:
            A dictionary reflecting only the key structure of the input.

    .. doctest::

        >>> keys_only_dict = get_nested_dict_keys_structure(adata.uns["config"]["general"])
        >>> print(keys_only_dict)

    Calls:
        get_nested_dict_keys_structure

    Called By:
        get_nested_dict_keys_structure

    Tags:
        utils
    """
    if not isinstance(dict_, dict):
        return  # Or you could return the value itself if you want to show non-dict values

    keys_only = {}
    for key, value in dict_.items():
        if isinstance(value, dict):
            keys_only[key] = get_nested_dict_keys_structure(value)
        else:
            keys_only[key] = {}  # Represents a leaf node (a value was here)
    return keys_only


def update_key_in_config(
            config: dict,
            key_to_update: str,
            new_value: object
        ) -> None:
    """
    Recursively update all keys named 'key_to_update' in a nested config
    dictionary if their type matches the type of 'new_value' (or they are None).

    Args:
        config (dict): The configuration dictionary to modify in-place.
        key_to_update (str): The key name to update.
        new_value (object): The new value to assign.

    Returns:
        None

    Calls:
        update_key_in_config

    Called By:
        update_key_in_config

    Tags:
        config, utils
    """
    for key, value in config.items():
        if isinstance(value, dict):
            update_key_in_config(value, key_to_update, new_value)
        elif key == key_to_update:
            if isinstance(value, type(new_value)) or value is None:
                config[key] = new_value
